import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiGo,
  SiHtml5,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiTailwindcss,
  SiThreedotjs,
  SiGreensock,
  SiRedux,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiDjango,
  SiFastapi,
  SiGraphql,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiFirebase,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiNginx,
  SiLinux,
  SiTerraform,
  SiSelenium,
  SiScrapy,
  SiJest,
  SiCypress,
  SiGit,
  SiVite,
  SiWebpack,
  SiFigma,
  SiJira,
  SiDatadog,
  SiSass,
  SiReactquery,
  SiChakraui,
  SiBootstrap,
  SiTensorflow,
  SiSvelte,
  SiRust,
  SiLua,
  SiSupabase,
  SiPrisma,
  SiQwik,
  SiGin,
  SiJsonwebtokens,
  SiVitest,
  SiPuppeteer,
  SiPrometheus,
  SiGrafana,
  SiAnsible,
  SiDigitalocean,
  SiMui,
  SiMantine,
  SiSqlalchemy,
  SiRabbitmq,
  SiApachekafka,
  SiSocketdotio,
  SiTrpc,
  SiBabel,
  SiEslint,
  SiNpm,
  SiPnpm,
  SiYarn,
  SiRadixui,
} from 'react-icons/si';

import { FaAws, FaCss3Alt } from 'react-icons/fa';
import { TbTestPipe, TbBrandGolang } from 'react-icons/tb';
import type { IconType } from 'react-icons';

const iconMap: Record<string, IconType> = {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiGo,
  SiHtml5,
  SiCss3: FaCss3Alt,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiTailwindcss,
  SiThreedotjs,
  SiGreensock,
  SiRedux,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiDjango,
  SiFastapi,
  SiGraphql,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiAmazonwebservices: FaAws,
  SiFirebase,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiNginx,
  SiLinux,
  SiTerraform,
  SiSelenium,
  SiScrapy,
  SiJest,
  SiCypress,
  SiGit,
  SiVite,
  SiWebpack,
  SiFigma,
  SiJira,
  SiDatadog,
  SiSass,
  SiReactquery,
  SiRecoil: SiReact, // Recoil uses React-like icon as fallback
  SiChakraui,
  SiBootstrap,
  SiTensorflow,
  SiSvelte,
  SiRust,
  SiLua,
  SiSupabase,
  SiPrisma,
  SiQwik,
  SiGin,
  SiJsonwebtokens,
  SiPlaywright: TbTestPipe,      // Playwright has no SI icon — use test pipe
  SiFiber: TbBrandGolang,        // Fiber is a Go framework — use Go brand icon
  SiMui,
  SiMantine,
  SiSqlalchemy,
  SiJotai: SiReact,              // Jotai has no SI icon — use React icon
  SiZustand: SiReact,            // Zustand has no SI icon — use React icon
  SiRabbitmq,
  SiApachekafka,
  SiSocketdotio,
  SiTrpc,
  SiBabel,
  SiEslint,
  SiNpm,
  SiPnpm,
  SiYarn,
  SiRadixui,
  SiVitest,
  SiPuppeteer,
  SiPrometheus,
  SiGrafana,
  SiAnsible,
  SiDigitalocean,
};

const colorMap: Record<string, string> = {
  SiTypescript: '#3178C6',
  SiJavascript: '#F7DF1E',
  SiPython: '#3776AB',
  SiGo: '#00ADD8',
  SiHtml5: '#E34F26',
  SiCss3: '#1572B6',
  SiReact: '#61DAFB',
  SiNextdotjs: '#FFFFFF',
  SiVuedotjs: '#4FC08D',
  SiAngular: '#DD0031',
  SiTailwindcss: '#06B6D4',
  SiThreedotjs: '#FFFFFF',
  SiGreensock: '#88CE02',
  SiRedux: '#764ABC',
  SiNodedotjs: '#339933',
  SiExpress: '#FFFFFF',
  SiNestjs: '#E0234E',
  SiDjango: '#092E20',
  SiFastapi: '#009688',
  SiGraphql: '#E10098',
  SiPostgresql: '#4169E1',
  SiMysql: '#4479A1',
  SiMongodb: '#47A248',
  SiRedis: '#DC382D',
  SiAmazonwebservices: '#FF9900',
  SiFirebase: '#FFCA28',
  SiDocker: '#2496ED',
  SiKubernetes: '#326CE5',
  SiGithubactions: '#2088FF',
  SiNginx: '#009639',
  SiLinux: '#FCC624',
  SiTerraform: '#7B42BC',
  SiSelenium: '#43B02A',
  SiScrapy: '#60A839',
  SiJest: '#C21325',
  SiCypress: '#69D3A7',
  SiGit: '#F05032',
  SiVite: '#646CFF',
  SiWebpack: '#8DD6F9',
  SiFigma: '#F24E1E',
  SiJira: '#0052CC',
  SiDatadog: '#632CA6',
  SiSass: '#CC6699',
  SiReactquery: '#FF4154',
  SiRecoil: '#3578E5',
  SiChakraui: '#319795',
  SiBootstrap: '#7952B3',
  SiTensorflow: '#FF6F00',
  SiPlaywright: '#2EAD33',
  SiSvelte: '#FF3E00',
  SiQwik: '#18B6F6',
  SiRust: '#CE422B',
  SiLua: '#00007C',
  SiSupabase: '#3ECF8E',
  SiPrisma: '#5A67D8',
  SiGin: '#00ADD8',
  SiFiber: '#00ACD7',
  SiJsonwebtokens: '#D63AFF',
  SiVitest: '#6E9F18',
  SiPuppeteer: '#40B5A4',
  SiPrometheus: '#E6522C',
  SiGrafana: '#F46800',
  SiAnsible: '#EE0000',
  SiDigitalocean: '#0080FF',
  SiRabbitmq: '#FF6600',
  SiApachekafka: '#FFFFFF',
  SiSocketdotio: '#FFFFFF',
  SiTrpc: '#398CCB',
  SiBabel: '#F9DC3E',
  SiEslint: '#4B32C3',
  SiNpm: '#CB3837',
  SiPnpm: '#F69220',
  SiYarn: '#2C8EBB',
  SiRadixui: '#FFFFFF',
  SiMui: '#007FFF',
  SiMantine: '#339AF0',
  SiSqlalchemy: '#D71F00',
  SiJotai: '#FFFFFF',
  SiZustand: '#FF6B35',
};

// Fallback for icons that don't exist in react-icons
const FallbackIcon = ({ size = 16 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" opacity={0.5}>
    <rect x="3" y="3" width="18" height="18" rx="3" fill="none" stroke="currentColor" strokeWidth="1.5" />
    <circle cx="12" cy="12" r="3" fill="currentColor" />
  </svg>
);

interface SkillIconProps {
  iconKey: string;
  size?: number;
  className?: string;
}

const SkillIcon = ({ iconKey, size = 16, className = '' }: SkillIconProps) => {
  const Icon = iconMap[iconKey];
  if (!Icon) return <FallbackIcon size={size} />;
  const color = colorMap[iconKey];
  return <Icon size={size} className={className} color={color} />;
};

export default SkillIcon;
